version: '3'
services:
  web:
    build: .
    command: bash
    environment:
      PORT: "4000"
    volumes:
      - ./apps:/apps
    working_dir: /apps
    ports:
      - "4000:4000"
    tty: true
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
