version: '3'
services:
  web:
    build: .
    command: bash
    ports:
      - '4000:4000'
    volumes:
      - ./apps:/apps
    working_dir: /apps
    environment:
      WEB_DB_PRESS_VOL_127_DB_HOST: db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
